config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "homes#index"
  resources :users, only: [:index, :edit, :update]
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability
  def initialize(user)
    user ||= User.new
    if user.user?
      can :manage, User, id: user.id
      cannot :index, User
    elsif user.admin?
      can :manage, :all
    else
      can :read, :all
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_attached_file :profile_picture
  validates_attachment :profile_picture,
    :presence => true,
    :size => { :in => 0..10.megabytes },
    :content_type => { :content_type => /^image\/(jpeg|png|gif|tiff)$/ }
  validates :name, :email, :role, presence: true

  ROLES = %w[admin user]

  def admin?
    role.zero?
  end

  def user?
    role == 1
  end

  def role=(value)
    value ||= 1
    super(value)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, alert: exception.message
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email, :password, :profile_picture, address: [:street_address, :city, :state, :zip_code, :phone_number]])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :email, :password, :current_password])
  end

  def after_sign_in_path_for(resource)
    if resource.admin?
      users_path
    else
      edit_user_path(resource)
    end
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  # GET /homes
  # GET /homes.json
  def index; end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource
  before_action :authenticate_user!

  def index
    @users = User.all
  end

  def edit
    @user = User.find(params[:id])
    render :edit
  end

  def update
    @user = User.find(params[:id])
    respond_to do |format|
     if @user.update_attributes(user_params)
        format.html { redirect_to edit_user_path(@user), notice: 'Updated.' }
      else
        format.html {
          flash[:alert] = "Something wrong"
          render :action => :edit
        }
      end
    end
  end

  private

  def user_params
    params.require(:user).permit([:name, :email, :password, :profile_picture,
                                  address: [:street_address, :phone_number,
                                            :city, :state, :zip_code]])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homes/index.html.erb
 <section id="hero">
  <div class="hero-container">
    <h1>Welcome to Regna</h1>
    <h2>We are team of talanted designers making websites with Bootstrap</h2>
    <a href="#about" class="btn-get-started">Get Started</a>
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UsersDemo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header id="header">
      <div class="container">

        <div id="logo" class="pull-left">
          <a href="<%= root_path %>"><%= image_tag 'logo.png' %></a>
          <!-- Uncomment below if you prefer to use a text logo -->
          <!--<h1><a href="#hero">Regna</a></h1>-->
        </div>

        <nav id="nav-menu-container">
          <ul class="nav-menu">
            <li class="menu-active"><a href="<%= root_path %>">Home</a></li>
            <%if user_signed_in? %>
              <li><%= link_to 'Log out', destroy_user_session_path, method: :delete %></li>
            <% else %>
              <li><%= link_to "Log in", new_session_path(User) %><br /></li>
              <li><%= link_to "Sign up", new_registration_path(User) %><br /></li>
            <% end %>
          </ul>
        </nav>
      </div>
    </header>
    <main id="main">
      <%= notice if notice.present? %>
      <%= alert if alert.present?%>
      <%= yield %>
    </main>
  </body>
</html>

app/views/users/edit.html.erb
<h2>Edit <%= @user.name.to_s.humanize %></h2>

<%= form_for(@user, html: { method: :put }) do |f| %>
<div class="content">
    <div class="container">
      <div class="row sp-xs-m-0">
        <div class="col-md-12">
          <div class="form-item-block">
            <div class="field">
              <%= f.label :name %>
              <%= f.text_field :name, autofocus: true, autocomplete: "email" %>
            </div>
          </div>
          <div class="form-item-block">
            <div class="field">
              <%= f.label :email %>
              <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
            </div>
          </div>
          <div class="form-item-block">
            <div class="fields">
              <%= f.fields_for :address, OpenStruct.new(f.object.address) do |a| %>
                <div class="field">
                    <label>Street address </label>
                    <%= a.text_field :street_address, id: :street_address %>
                </div>
                <div class="field">
                    <label>City </label>
                    <%= a.text_field :city, id: :city %>
                </div>
                <div class="two wide field">
                    <label>State </label>
                    <%= a.text_field :state, id: :state %>
                </div>

                <div class="field">
                    <label>Zip </label>
                    <%= a.number_field :zip_code, id: :zip_code %>
                </div>
                <% if @user == current_user  %>
                  <div class="field">
                      <label>Phone Number </label>
                      <%= a.text_field :phone_number %>
                  </div>
                <% end %>
              <% end %>
            </div>
          </div>
          <div class="field">
            <%= f.label :profile_picture %>
            <%= f.file_field :profile_picture %>
          </div>
          <div class="actions">
            <%= f.submit "Update", class: 'btn btn-success' %>
          </div>
        </div>
      </div>
    </div>
</div>

<% end %>
<% unless @user.admin? %>
  <h3>Cancel my account</h3>

  <p>Unhappy? <%= button_to "Cancel my account", registration_path(@user), data: { confirm: "Are you sure?" }, method: :delete %></p>
<% end %>

app/views/users/index.html.erb
<h2>Users List</h2>
<table class="table table-striped">
  <thead class="thead-dark">
    <tr>
      <th class="col">Name</th>
      <th class="col">email</th>
      <th class="col">Street Address</th>
      <th class="col">City</th>
      <th class="col">State</th>
      <th class="col">Zip Code</th>
      <th class="col">Phone Number/th>
      <th class="col">Profile Picture</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td class="col"><%= user.name %></td>
        <td class="col"><%= user.email %></td>
        <td class="col"><%= user.address['street_address'] %></td>
        <td class="col"><%= user.address['city'] %></td>
        <td class="col"><%= user.address['state'] %></td>
        <td class="col"><%= user.address['zip_code'] %></td>
        <td class="col"><%= user.address['phone_number'] %></td>
        <td class="col"><%= image_tag user.profile_picture.url(:original) %></td>
        <td class="col">
          <%= link_to 'Edit', edit_user_path(user), class: "btn  btn-warning" %>
          <%= link_to 'Destroy', users_path(user), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>